### ISSUE TITLE
No dummy data plx

### ISSUE THREAD

**Issue by ju5tu5** [tom-2810/the-startup-responsive-interactieve-website#10]
<img width="281" alt="image" src="https://user-images.githubusercontent.com/140124/213674715-8665d2d2-7f9c-40fa-aea1-0d21fe78f887.png">

**Comment by tom-2810** [comment]
Dummy data is vervangen met nuttige informatie. Ook is er geen lorem ipsum (meer 😐😆) aanwezig.
